#!/bin/bash

# Script to extract Salesforce authentication details from SF CLI and append to .env file
# Usage: ./sfauth2env.sh [org-alias]
# If no org-alias provided, uses default org

set -e

ORG_ALIAS=${1:-""}

echo "🔍 Getting Salesforce org authentication details..."

# Build the sf command
if [ -n "$ORG_ALIAS" ]; then
    SF_CMD="sf org display --target-org $ORG_ALIAS --json"
    echo "Using org alias: $ORG_ALIAS"
else
    SF_CMD="sf org display --json"
    echo "Using default org"
fi

# Execute SF CLI command and extract values with jq
echo "Running: $SF_CMD"
ORG_INFO=$($SF_CMD)

# Extract the required values
SESSION_ID=$(echo "$ORG_INFO" | jq -r '.result.accessToken // .result.sessionId // empty')
INSTANCE_URL=$(echo "$ORG_INFO" | jq -r '.result.instanceUrl // empty')
API_VERSION=$(echo "$ORG_INFO" | jq -r '.result.apiVersion // "59.0"')
ORG_ID=$(echo "$ORG_INFO" | jq -r '.result.id // empty')

# Validate extracted values
if [ -z "$SESSION_ID" ] || [ "$SESSION_ID" = "null" ]; then
    echo "❌ Error: Could not extract session ID from SF CLI output"
    echo "Make sure you're authenticated to Salesforce: sf org login web"
    exit 1
fi

if [ -z "$INSTANCE_URL" ] || [ "$INSTANCE_URL" = "null" ]; then
    echo "❌ Error: Could not extract instance URL from SF CLI output"
    exit 1
fi

if [ -z "$ORG_ID" ] || [ "$ORG_ID" = "null" ]; then
    echo "❌ Error: Could not extract organization ID from SF CLI output"
    exit 1
fi

echo "✅ Extracted values:"
echo "   Session ID: ${SESSION_ID:0:10}... (truncated)"
echo "   Instance URL: $INSTANCE_URL"
echo "   API Version: $API_VERSION"
echo "   Org ID: $ORG_ID"

# Create .env if it doesn't exist
if [ ! -f .env ]; then
    echo "📄 Creating .env file..."
    touch .env
fi

# Remove any existing SF_* entries from .env to avoid duplicates
echo "🧹 Removing any existing SF_* entries from .env..."
sed -i.bak '/^SF_SESSION_ID=/d; /^SF_INSTANCE_URL=/d; /^SF_API_VERSION=/d; /^SF_ORG_ID=/d' .env

# Append new SF authentication variables to .env
echo "📝 Appending SF CLI authentication to .env..."
{
    echo ""
    echo "# SF CLI Authentication (generated by sfauth2env.sh)"
    echo "SF_SESSION_ID=$SESSION_ID"
    echo "SF_INSTANCE_URL=$INSTANCE_URL"
    echo "SF_API_VERSION=$API_VERSION"
    echo "SF_ORG_ID=$ORG_ID"
} >> .env

echo "✅ Successfully updated .env with SF CLI authentication details!"
echo "🚀 You can now run: mvn spring-boot:run" 
